// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnboardingWeatherAPI.Models.Shared;

#nullable disable

namespace OnboardingWeatherAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("OnboardingWeatherAPI.Models.City", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Kaunas"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Vilnius"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Klaipėda"
                        });
                });

            modelBuilder.Entity("OnboardingWeatherAPI.Models.FactualWeatherPrediction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("CityId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<long>("ForecasterId")
                        .HasColumnType("bigint");

                    b.Property<double>("Temperature")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("ForecasterId");

                    b.ToTable("FactualWeatherPredictions");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CityId = 1L,
                            Date = new DateTime(2022, 4, 12, 16, 20, 5, 47, DateTimeKind.Local).AddTicks(1450),
                            ForecasterId = 1L,
                            Temperature = 12.5
                        },
                        new
                        {
                            Id = 2L,
                            CityId = 1L,
                            Date = new DateTime(2022, 4, 11, 16, 20, 5, 47, DateTimeKind.Local).AddTicks(1481),
                            ForecasterId = 1L,
                            Temperature = 11.199999999999999
                        },
                        new
                        {
                            Id = 3L,
                            CityId = 2L,
                            Date = new DateTime(2022, 4, 12, 16, 20, 5, 47, DateTimeKind.Local).AddTicks(1484),
                            ForecasterId = 1L,
                            Temperature = 10.199999999999999
                        });
                });

            modelBuilder.Entity("OnboardingWeatherAPI.Models.Forecaster", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Forecasters");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "OpenWeatherMap"
                        });
                });

            modelBuilder.Entity("OnboardingWeatherAPI.Models.FactualWeatherPrediction", b =>
                {
                    b.HasOne("OnboardingWeatherAPI.Models.City", "City")
                        .WithMany("FactualWeatherPredictions")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnboardingWeatherAPI.Models.Forecaster", "Forecaster")
                        .WithMany("FactualWeatherPredictions")
                        .HasForeignKey("ForecasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Forecaster");
                });

            modelBuilder.Entity("OnboardingWeatherAPI.Models.City", b =>
                {
                    b.Navigation("FactualWeatherPredictions");
                });

            modelBuilder.Entity("OnboardingWeatherAPI.Models.Forecaster", b =>
                {
                    b.Navigation("FactualWeatherPredictions");
                });
#pragma warning restore 612, 618
        }
    }
}
